//go:build specguardian

// Code generated by spec-guardian. DO NOT EDIT.
package specguardian_test

import (
	"fmt"
	"testing"

	"github.com/mrasu/spec-guardian/guardian"
)

func TestIcebergTable_Append_Conformance(t *testing.T) {
	cases := LoadIcebergTableCases(t, "testdata/icebergtable_append_cases_generated.json")

	for _, testCase := range cases {
		t.Run(testCase.Name, func(t *testing.T) {
			controller := guardian.NewInjectionController("IcebergTable.Append")
			environment := NewIcebergTableConformanceEnvironment(t, controller)
			environment.PrepareAppendCase(t)

			input := environment.BuildAppendInput(t, testCase.Input)
			for faultNumber := range controller.Attempts() {
				t.Run(fmt.Sprintf("fault:%d", faultNumber), func(t *testing.T) {
					environment.PrepareAppendAttempt(t, testCase.Input)

					var actionOutput IcebergTableAppendOutput
					var actionErr error
					func() {
						defer controller.InjectFaultAt(faultNumber)()
						actionOutput, actionErr = environment.ExecuteAppend(t.Context(), input)
					}()

					observedState := environment.ObserveAppendState(t, testCase.Input, actionOutput, actionErr)
					allowedStates := environment.BuildAllowedAppendStates(t, testCase.Allowed)

					guardian.AssertAllowed(t, allowedStates, observedState, controller.Events())
				})
			}
		})
	}
}

func TestIcebergTable_Delete_Conformance(t *testing.T) {
	cases := LoadIcebergTableCases(t, "testdata/icebergtable_delete_cases_generated.json")

	for _, testCase := range cases {
		t.Run(testCase.Name, func(t *testing.T) {
			controller := guardian.NewInjectionController("IcebergTable.Delete")
			environment := NewIcebergTableConformanceEnvironment(t, controller)
			environment.PrepareDeleteCase(t)

			input := environment.BuildDeleteInput(t, testCase.Input)
			for faultNumber := range controller.Attempts() {
				t.Run(fmt.Sprintf("fault:%d", faultNumber), func(t *testing.T) {
					environment.PrepareDeleteAttempt(t, testCase.Input)

					var actionOutput IcebergTableDeleteOutput
					var actionErr error
					func() {
						defer controller.InjectFaultAt(faultNumber)()
						actionOutput, actionErr = environment.ExecuteDelete(t.Context(), input)
					}()

					observedState := environment.ObserveDeleteState(t, testCase.Input, actionOutput, actionErr)
					allowedStates := environment.BuildAllowedDeleteStates(t, testCase.Allowed)

					guardian.AssertAllowed(t, allowedStates, observedState, controller.Events())
				})
			}
		})
	}
}

func TestIcebergTable_Overwrite_Conformance(t *testing.T) {
	cases := LoadIcebergTableCases(t, "testdata/icebergtable_overwrite_cases_generated.json")

	for _, testCase := range cases {
		t.Run(testCase.Name, func(t *testing.T) {
			controller := guardian.NewInjectionController("IcebergTable.Overwrite")
			environment := NewIcebergTableConformanceEnvironment(t, controller)
			environment.PrepareOverwriteCase(t)

			input := environment.BuildOverwriteInput(t, testCase.Input)
			for faultNumber := range controller.Attempts() {
				t.Run(fmt.Sprintf("fault:%d", faultNumber), func(t *testing.T) {
					environment.PrepareOverwriteAttempt(t, testCase.Input)

					var actionOutput IcebergTableOverwriteOutput
					var actionErr error
					func() {
						defer controller.InjectFaultAt(faultNumber)()
						actionOutput, actionErr = environment.ExecuteOverwrite(t.Context(), input)
					}()

					observedState := environment.ObserveOverwriteState(t, testCase.Input, actionOutput, actionErr)
					allowedStates := environment.BuildAllowedOverwriteStates(t, testCase.Allowed)

					guardian.AssertAllowed(t, allowedStates, observedState, controller.Events())
				})
			}
		})
	}
}
