//go:build specguardian

// Code generated by spec-guardian. DO NOT EDIT.
package specguardian_test

import (
	"context"
	"testing"

	"github.com/mrasu/spec-guardian/guardian"
	"github.com/mrasu/spec-guardian/guardian/gcmp"
)

// IcebergTableActions describes the application methods exercised by this role.
// This generated interface is the contract implemented by the application adapter.
type IcebergTableActions interface {
	Append(context.Context, IcebergTableAppendInput) (IcebergTableAppendOutput, error)
	Delete(context.Context, IcebergTableDeleteInput) (IcebergTableDeleteOutput, error)
	Overwrite(context.Context, IcebergTableOverwriteInput) (IcebergTableOverwriteOutput, error)
}

// IcebergTableConformanceEnvironment joins the application action adapter with its test resources.
type IcebergTableConformanceEnvironment struct {
	Actions IcebergTableActions
	*IcebergTableEnvironment
}

// NewIcebergTableConformanceEnvironment builds the adapter and resources for a conformance case.
func NewIcebergTableConformanceEnvironment(t *testing.T, controller *guardian.InjectionController) *IcebergTableConformanceEnvironment {
	t.Helper()
	actions, environment := BuildIcebergTableConformanceComponents(t, controller)

	return &IcebergTableConformanceEnvironment{
		Actions:                 actions,
		IcebergTableEnvironment: environment,
	}
}

// LoadIcebergTableCases reads generated cases from filepath.
func LoadIcebergTableCases(t *testing.T, filepath string) []IcebergTableCase {
	t.Helper()
	return guardian.LoadCases[IcebergTableCase](t, filepath)
}

// PrepareAppendCase sets up one case and registers its cleanup.
func (e *IcebergTableConformanceEnvironment) PrepareAppendCase(t *testing.T) {
	e.SetupAppendCase(t)
	t.Cleanup(func() {
		e.CleanupAppendCase(t)
	})
}

// PrepareAppendAttempt sets up one fault attempt and registers its cleanup.
func (e *IcebergTableConformanceEnvironment) PrepareAppendAttempt(t *testing.T, input FizzbeeIcebergTableState) {
	e.SetupAppendAttempt(t, input)
	t.Cleanup(func() {
		e.CleanupAppendAttempt(t)
	})
}

// ExecuteAppend invokes the application action.
func (e *IcebergTableConformanceEnvironment) ExecuteAppend(ctx context.Context, input IcebergTableAppendInput) (IcebergTableAppendOutput, error) {
	return e.Actions.Append(ctx, input)
}

// ObserveAppendState collects the state and output visible after the action.
func (e *IcebergTableConformanceEnvironment) ObserveAppendState(t *testing.T, input FizzbeeIcebergTableState, output IcebergTableAppendOutput, actionErr error) guardian.ObservedState[*IcebergTableObservedState] {
	observedState := e.ObserveCurrentState(t)
	resultState := e.BuildObservedAppendState(t, observedState, input, output, actionErr)

	return guardian.NewObservedState(&resultState)
}

// BuildAllowedAppendStates maps FizzBee outcomes to comparable states.
func (e *IcebergTableConformanceEnvironment) BuildAllowedAppendStates(t *testing.T, allowed []FizzbeeIcebergTableState) []guardian.ComparisonState[*IcebergTableComparisonState] {
	allowedStates := make([]guardian.ComparisonState[*IcebergTableComparisonState], len(allowed))
	for i, allowed := range allowed {
		allowedState := e.BuildAllowedAppendState(t, allowed)
		allowedStates[i] = guardian.NewComparisonState(&allowedState)
	}

	return allowedStates
}

// PrepareDeleteCase sets up one case and registers its cleanup.
func (e *IcebergTableConformanceEnvironment) PrepareDeleteCase(t *testing.T) {
	e.SetupDeleteCase(t)
	t.Cleanup(func() {
		e.CleanupDeleteCase(t)
	})
}

// PrepareDeleteAttempt sets up one fault attempt and registers its cleanup.
func (e *IcebergTableConformanceEnvironment) PrepareDeleteAttempt(t *testing.T, input FizzbeeIcebergTableState) {
	e.SetupDeleteAttempt(t, input)
	t.Cleanup(func() {
		e.CleanupDeleteAttempt(t)
	})
}

// ExecuteDelete invokes the application action.
func (e *IcebergTableConformanceEnvironment) ExecuteDelete(ctx context.Context, input IcebergTableDeleteInput) (IcebergTableDeleteOutput, error) {
	return e.Actions.Delete(ctx, input)
}

// ObserveDeleteState collects the state and output visible after the action.
func (e *IcebergTableConformanceEnvironment) ObserveDeleteState(t *testing.T, input FizzbeeIcebergTableState, output IcebergTableDeleteOutput, actionErr error) guardian.ObservedState[*IcebergTableObservedState] {
	observedState := e.ObserveCurrentState(t)
	resultState := e.BuildObservedDeleteState(t, observedState, input, output, actionErr)

	return guardian.NewObservedState(&resultState)
}

// BuildAllowedDeleteStates maps FizzBee outcomes to comparable states.
func (e *IcebergTableConformanceEnvironment) BuildAllowedDeleteStates(t *testing.T, allowed []FizzbeeIcebergTableState) []guardian.ComparisonState[*IcebergTableComparisonState] {
	allowedStates := make([]guardian.ComparisonState[*IcebergTableComparisonState], len(allowed))
	for i, allowed := range allowed {
		allowedState := e.BuildAllowedDeleteState(t, allowed)
		allowedStates[i] = guardian.NewComparisonState(&allowedState)
	}

	return allowedStates
}

// PrepareOverwriteCase sets up one case and registers its cleanup.
func (e *IcebergTableConformanceEnvironment) PrepareOverwriteCase(t *testing.T) {
	e.SetupOverwriteCase(t)
	t.Cleanup(func() {
		e.CleanupOverwriteCase(t)
	})
}

// PrepareOverwriteAttempt sets up one fault attempt and registers its cleanup.
func (e *IcebergTableConformanceEnvironment) PrepareOverwriteAttempt(t *testing.T, input FizzbeeIcebergTableState) {
	e.SetupOverwriteAttempt(t, input)
	t.Cleanup(func() {
		e.CleanupOverwriteAttempt(t)
	})
}

// ExecuteOverwrite invokes the application action.
func (e *IcebergTableConformanceEnvironment) ExecuteOverwrite(ctx context.Context, input IcebergTableOverwriteInput) (IcebergTableOverwriteOutput, error) {
	return e.Actions.Overwrite(ctx, input)
}

// ObserveOverwriteState collects the state and output visible after the action.
func (e *IcebergTableConformanceEnvironment) ObserveOverwriteState(t *testing.T, input FizzbeeIcebergTableState, output IcebergTableOverwriteOutput, actionErr error) guardian.ObservedState[*IcebergTableObservedState] {
	observedState := e.ObserveCurrentState(t)
	resultState := e.BuildObservedOverwriteState(t, observedState, input, output, actionErr)

	return guardian.NewObservedState(&resultState)
}

// BuildAllowedOverwriteStates maps FizzBee outcomes to comparable states.
func (e *IcebergTableConformanceEnvironment) BuildAllowedOverwriteStates(t *testing.T, allowed []FizzbeeIcebergTableState) []guardian.ComparisonState[*IcebergTableComparisonState] {
	allowedStates := make([]guardian.ComparisonState[*IcebergTableComparisonState], len(allowed))
	for i, allowed := range allowed {
		allowedState := e.BuildAllowedOverwriteState(t, allowed)
		allowedStates[i] = guardian.NewComparisonState(&allowedState)
	}

	return allowedStates
}

// IcebergTableCase is one generated input with its allowed outcomes.
type IcebergTableCase struct {
	Name    string                     `json:"name"`
	Input   FizzbeeIcebergTableState   `json:"input"`
	Allowed []FizzbeeIcebergTableState `json:"allowed"`
}

// FizzbeeIcebergTableState contains the model parameters and fields for this role.
type FizzbeeIcebergTableState struct {
	Params IcebergTableParams `json:"params"`
	Fields IcebergTableFields `json:"fields"`
}

// IcebergTableParams contains each role's model parameters.
type IcebergTableParams struct {
	Writer1      IcebergTableWriter1Params      `json:"Writer1"`
	Writer2      IcebergTableWriter2Params      `json:"Writer2"`
	IcebergTable IcebergTableIcebergTableParams `json:"IcebergTable"`
}

// IcebergTableWriter1Params contains model parameters for Writer1.
type IcebergTableWriter1Params struct {
	ID         int  `json:"ID"`
	Background bool `json:"background"`
}

// IcebergTableWriter2Params contains model parameters for Writer2.
type IcebergTableWriter2Params struct {
	ID         int  `json:"ID"`
	Background bool `json:"background"`
}

// IcebergTableIcebergTableParams contains model parameters for IcebergTable.
type IcebergTableIcebergTableParams struct {
	OperationType string `json:"operation_type"`
	Predicate     []any  `json:"predicate"`
	Row           []any  `json:"row"`
	SetValues     []any  `json:"set_values"`
	Writer        string `json:"writer"`
}

// IcebergTableFields contains each role's model fields.
type IcebergTableFields struct {
	ObjectStore  IcebergTableObjectStoreFields  `json:"ObjectStore"`
	Catalog      IcebergTableCatalogFields      `json:"Catalog"`
	Writer1      IcebergTableWriter1Fields      `json:"Writer1"`
	Writer2      IcebergTableWriter2Fields      `json:"Writer2"`
	IcebergTable IcebergTableIcebergTableFields `json:"IcebergTable"`
}

// IcebergTableObjectStoreFields contains model fields for ObjectStore.
type IcebergTableObjectStoreFields struct {
	Objects map[string]any `json:"objects"`
}

// IcebergTableCatalogFields contains model fields for Catalog.
type IcebergTableCatalogFields struct {
	MetadataLocation string `json:"metadata_location"`
}

// IcebergTableWriter1Fields contains model fields for Writer1.
type IcebergTableWriter1Fields struct {
	Op map[string]any `json:"op"`
}

// IcebergTableWriter2Fields contains model fields for Writer2.
type IcebergTableWriter2Fields struct {
	Op map[string]any `json:"op"`
}

// IcebergTableIcebergTableFields contains model fields for IcebergTable.
type IcebergTableIcebergTableFields struct {
	Result string `json:"result"`
}

// IcebergTableObservedState holds values observed from the application.
type IcebergTableObservedState struct {
	Params IcebergTableObservedParams
	Fields IcebergTableObservedFields
}

// IcebergTableObservedParams contains observed parameters for each role.
type IcebergTableObservedParams struct {
	Writer1      IcebergTableWriter1ObservedParams
	Writer2      IcebergTableWriter2ObservedParams
	IcebergTable IcebergTableIcebergTableObservedParams
}

// IcebergTableWriter1ObservedParams contains observed parameters for Writer1.
type IcebergTableWriter1ObservedParams struct {
	ID         *gcmp.ObservedField[int]
	Background *gcmp.ObservedField[bool]
}

// IcebergTableWriter2ObservedParams contains observed parameters for Writer2.
type IcebergTableWriter2ObservedParams struct {
	ID         *gcmp.ObservedField[int]
	Background *gcmp.ObservedField[bool]
}

// IcebergTableIcebergTableObservedParams contains observed parameters for IcebergTable.
type IcebergTableIcebergTableObservedParams struct {
	OperationType *gcmp.ObservedField[string]
	Predicate     *gcmp.ObservedField[any]
	Row           *gcmp.ObservedField[[]any]
	SetValues     *gcmp.ObservedField[any]
	Writer        *gcmp.ObservedField[string]
}

// IcebergTableObservedFields contains observed fields for each role.
type IcebergTableObservedFields struct {
	ObjectStore  IcebergTableObjectStoreObservedFields
	Catalog      IcebergTableCatalogObservedFields
	Writer1      IcebergTableWriter1ObservedFields
	Writer2      IcebergTableWriter2ObservedFields
	IcebergTable IcebergTableIcebergTableObservedFields
}

// IcebergTableObjectStoreObservedFields contains observed fields for ObjectStore.
type IcebergTableObjectStoreObservedFields struct {
	Objects *gcmp.ObservedField[map[string]any]
}

// IcebergTableCatalogObservedFields contains observed fields for Catalog.
type IcebergTableCatalogObservedFields struct {
	MetadataLocation *gcmp.ObservedField[string]
}

// IcebergTableWriter1ObservedFields contains observed fields for Writer1.
type IcebergTableWriter1ObservedFields struct {
	Op *gcmp.ObservedField[map[string]any]
}

// IcebergTableWriter2ObservedFields contains observed fields for Writer2.
type IcebergTableWriter2ObservedFields struct {
	Op *gcmp.ObservedField[map[string]any]
}

// IcebergTableIcebergTableObservedFields contains observed fields for IcebergTable.
type IcebergTableIcebergTableObservedFields struct {
	Result *gcmp.ObservedField[string]
}

// IcebergTableComparisonState configures checks for an allowed model state.
type IcebergTableComparisonState struct {
	Params IcebergTableComparisonParams
	Fields IcebergTableComparisonFields
}

// ExpectedState identifies the FizzBee state type compared with this state.
func (actual *IcebergTableComparisonState) ExpectedState() FizzbeeIcebergTableState {
	return FizzbeeIcebergTableState{}
}

// IcebergTableComparisonParams contains parameter comparisons for each role.
type IcebergTableComparisonParams struct {
	Writer1      IcebergTableWriter1ComparisonParams
	Writer2      IcebergTableWriter2ComparisonParams
	IcebergTable IcebergTableIcebergTableComparisonParams
}

// IcebergTableWriter1ComparisonParams contains parameter comparisons for Writer1.
type IcebergTableWriter1ComparisonParams struct {
	ID         *gcmp.ComparisonField[int]
	Background *gcmp.ComparisonField[bool]
}

// IcebergTableWriter2ComparisonParams contains parameter comparisons for Writer2.
type IcebergTableWriter2ComparisonParams struct {
	ID         *gcmp.ComparisonField[int]
	Background *gcmp.ComparisonField[bool]
}

// IcebergTableIcebergTableComparisonParams contains parameter comparisons for IcebergTable.
type IcebergTableIcebergTableComparisonParams struct {
	OperationType *gcmp.ComparisonField[string]
	Predicate     *gcmp.ComparisonField[any]
	Row           *gcmp.ComparisonField[[]any]
	SetValues     *gcmp.ComparisonField[any]
	Writer        *gcmp.ComparisonField[string]
}

// IcebergTableComparisonFields contains field comparisons for each role.
type IcebergTableComparisonFields struct {
	ObjectStore  IcebergTableObjectStoreComparisonFields
	Catalog      IcebergTableCatalogComparisonFields
	Writer1      IcebergTableWriter1ComparisonFields
	Writer2      IcebergTableWriter2ComparisonFields
	IcebergTable IcebergTableIcebergTableComparisonFields
}

// IcebergTableObjectStoreComparisonFields contains field comparisons for ObjectStore.
type IcebergTableObjectStoreComparisonFields struct {
	Objects *gcmp.ComparisonField[map[string]any]
}

// IcebergTableCatalogComparisonFields contains field comparisons for Catalog.
type IcebergTableCatalogComparisonFields struct {
	MetadataLocation *gcmp.ComparisonField[string]
}

// IcebergTableWriter1ComparisonFields contains field comparisons for Writer1.
type IcebergTableWriter1ComparisonFields struct {
	Op *gcmp.ComparisonField[map[string]any]
}

// IcebergTableWriter2ComparisonFields contains field comparisons for Writer2.
type IcebergTableWriter2ComparisonFields struct {
	Op *gcmp.ComparisonField[map[string]any]
}

// IcebergTableIcebergTableComparisonFields contains field comparisons for IcebergTable.
type IcebergTableIcebergTableComparisonFields struct {
	Result *gcmp.ComparisonField[string]
}
