//go:build specguardian

// Code generated by spec-guardian. DO NOT EDIT.
package specguardian_test

import (
	"context"
	"testing"

	"github.com/mrasu/spec-guardian/guardian"
	"github.com/mrasu/spec-guardian/guardian/gcmp"
)

// DeliveryServerActions describes the application methods exercised by this role.
// This generated interface is the contract implemented by the application adapter.
type DeliveryServerActions interface {
	Deliver(context.Context, DeliveryServerDeliverInput) (DeliveryServerDeliverOutput, error)
}

// DeliveryServerConformanceEnvironment joins the application action adapter with its test resources.
type DeliveryServerConformanceEnvironment struct {
	Actions DeliveryServerActions
	*DeliveryServerEnvironment
}

// NewDeliveryServerConformanceEnvironment builds the adapter and resources for a conformance case.
func NewDeliveryServerConformanceEnvironment(t *testing.T, controller *guardian.InjectionController) *DeliveryServerConformanceEnvironment {
	t.Helper()
	actions, environment := BuildDeliveryServerConformanceComponents(t, controller)

	return &DeliveryServerConformanceEnvironment{
		Actions:                   actions,
		DeliveryServerEnvironment: environment,
	}
}

// LoadDeliveryServerCases reads generated cases from filepath.
func LoadDeliveryServerCases(t *testing.T, filepath string) []DeliveryServerCase {
	t.Helper()
	return guardian.LoadCases[DeliveryServerCase](t, filepath)
}

// PrepareDeliverCase sets up one case and registers its cleanup.
func (e *DeliveryServerConformanceEnvironment) PrepareDeliverCase(t *testing.T) {
	e.SetupDeliverCase(t)
	t.Cleanup(func() {
		e.CleanupDeliverCase(t)
	})
}

// PrepareDeliverAttempt sets up one fault attempt and registers its cleanup.
func (e *DeliveryServerConformanceEnvironment) PrepareDeliverAttempt(t *testing.T, input FizzbeeDeliveryServerState) {
	e.SetupDeliverAttempt(t, input)
	t.Cleanup(func() {
		e.CleanupDeliverAttempt(t)
	})
}

// ExecuteDeliver invokes the application action.
func (e *DeliveryServerConformanceEnvironment) ExecuteDeliver(ctx context.Context, input DeliveryServerDeliverInput) (DeliveryServerDeliverOutput, error) {
	return e.Actions.Deliver(ctx, input)
}

// ObserveDeliverState collects the state and output visible after the action.
func (e *DeliveryServerConformanceEnvironment) ObserveDeliverState(t *testing.T, input FizzbeeDeliveryServerState, output DeliveryServerDeliverOutput, actionErr error) guardian.ObservedState[*DeliveryServerObservedState] {
	observedState := e.ObserveCurrentState(t)
	resultState := e.BuildObservedDeliverState(t, observedState, input, output, actionErr)

	return guardian.NewObservedState(&resultState)
}

// BuildAllowedDeliverStates maps FizzBee outcomes to comparable states.
func (e *DeliveryServerConformanceEnvironment) BuildAllowedDeliverStates(t *testing.T, allowed []FizzbeeDeliveryServerState) []guardian.ComparisonState[*DeliveryServerComparisonState] {
	allowedStates := make([]guardian.ComparisonState[*DeliveryServerComparisonState], len(allowed))
	for i, allowed := range allowed {
		allowedState := e.BuildAllowedDeliverState(t, allowed)
		allowedStates[i] = guardian.NewComparisonState(&allowedState)
	}

	return allowedStates
}

// DeliveryServerCase is one generated input with its allowed outcomes.
type DeliveryServerCase struct {
	Name    string                       `json:"name"`
	Input   FizzbeeDeliveryServerState   `json:"input"`
	Allowed []FizzbeeDeliveryServerState `json:"allowed"`
}

// FizzbeeDeliveryServerState contains the model parameters and fields for this role.
type FizzbeeDeliveryServerState struct {
	Params DeliveryServerParams `json:"params"`
	Fields DeliveryServerFields `json:"fields"`
}

// DeliveryServerParams contains each role's model parameters.
type DeliveryServerParams struct {
}

// DeliveryServerFields contains each role's model fields.
type DeliveryServerFields struct {
	DynamoDB          DeliveryServerDynamoDBFields          `json:"DynamoDB"`
	MySQL             DeliveryServerMySQLFields             `json:"MySQL"`
	RequestPreparator DeliveryServerRequestPreparatorFields `json:"RequestPreparator"`
	DeliveryServer    DeliveryServerDeliveryServerFields    `json:"DeliveryServer"`
}

// DeliveryServerDynamoDBFields contains model fields for DynamoDB.
type DeliveryServerDynamoDBFields struct {
	DeliveryRecords         map[string]any `json:"delivery_records"`
	OrderIdempotencyRecords map[string]any `json:"order_idempotency_records"`
}

// DeliveryServerMySQLFields contains model fields for MySQL.
type DeliveryServerMySQLFields struct {
	DeliveryPreparedCount int            `json:"delivery_prepared_count"`
	NextOrderId           int            `json:"next_order_id"`
	OrderRecords          map[string]any `json:"order_records"`
}

// DeliveryServerRequestPreparatorFields contains model fields for RequestPreparator.
type DeliveryServerRequestPreparatorFields struct {
	SecondDeliveryData            string `json:"second_delivery_data"`
	SecondDeliveryRequestPrepared bool   `json:"second_delivery_request_prepared"`
	SecondOrderPayload            string `json:"second_order_payload"`
	SecondOrderRequestPrepared    bool   `json:"second_order_request_prepared"`
}

// DeliveryServerDeliveryServerFields contains model fields for DeliveryServer.
type DeliveryServerDeliveryServerFields struct {
	OrderId             *int   `json:"order_id"`
	RequestDeliveryData string `json:"request_delivery_data"`
	Result              string `json:"result"`
}

// DeliveryServerObservedState holds values observed from the application.
type DeliveryServerObservedState struct {
	Params DeliveryServerObservedParams
	Fields DeliveryServerObservedFields
}

// DeliveryServerObservedParams contains observed parameters for each role.
type DeliveryServerObservedParams struct {
}

// DeliveryServerObservedFields contains observed fields for each role.
type DeliveryServerObservedFields struct {
	DynamoDB          DeliveryServerDynamoDBObservedFields
	MySQL             DeliveryServerMySQLObservedFields
	RequestPreparator DeliveryServerRequestPreparatorObservedFields
	DeliveryServer    DeliveryServerDeliveryServerObservedFields
}

// DeliveryServerDynamoDBObservedFields contains observed fields for DynamoDB.
type DeliveryServerDynamoDBObservedFields struct {
	DeliveryRecords         *gcmp.ObservedField[map[string]any]
	OrderIdempotencyRecords *gcmp.ObservedField[map[string]any]
}

// DeliveryServerMySQLObservedFields contains observed fields for MySQL.
type DeliveryServerMySQLObservedFields struct {
	DeliveryPreparedCount *gcmp.ObservedField[int]
	NextOrderId           *gcmp.ObservedField[int]
	OrderRecords          *gcmp.ObservedField[map[string]any]
}

// DeliveryServerRequestPreparatorObservedFields contains observed fields for RequestPreparator.
type DeliveryServerRequestPreparatorObservedFields struct {
	SecondDeliveryData            *gcmp.ObservedField[string]
	SecondDeliveryRequestPrepared *gcmp.ObservedField[bool]
	SecondOrderPayload            *gcmp.ObservedField[string]
	SecondOrderRequestPrepared    *gcmp.ObservedField[bool]
}

// DeliveryServerDeliveryServerObservedFields contains observed fields for DeliveryServer.
type DeliveryServerDeliveryServerObservedFields struct {
	OrderId             *gcmp.ObservedField[*int]
	RequestDeliveryData *gcmp.ObservedField[string]
	Result              *gcmp.ObservedField[string]
}

// DeliveryServerComparisonState configures checks for an allowed model state.
type DeliveryServerComparisonState struct {
	Params DeliveryServerComparisonParams
	Fields DeliveryServerComparisonFields
}

// ExpectedState identifies the FizzBee state type compared with this state.
func (actual *DeliveryServerComparisonState) ExpectedState() FizzbeeDeliveryServerState {
	return FizzbeeDeliveryServerState{}
}

// DeliveryServerComparisonParams contains parameter comparisons for each role.
type DeliveryServerComparisonParams struct {
}

// DeliveryServerComparisonFields contains field comparisons for each role.
type DeliveryServerComparisonFields struct {
	DynamoDB          DeliveryServerDynamoDBComparisonFields
	MySQL             DeliveryServerMySQLComparisonFields
	RequestPreparator DeliveryServerRequestPreparatorComparisonFields
	DeliveryServer    DeliveryServerDeliveryServerComparisonFields
}

// DeliveryServerDynamoDBComparisonFields contains field comparisons for DynamoDB.
type DeliveryServerDynamoDBComparisonFields struct {
	DeliveryRecords         *gcmp.ComparisonField[map[string]any]
	OrderIdempotencyRecords *gcmp.ComparisonField[map[string]any]
}

// DeliveryServerMySQLComparisonFields contains field comparisons for MySQL.
type DeliveryServerMySQLComparisonFields struct {
	DeliveryPreparedCount *gcmp.ComparisonField[int]
	NextOrderId           *gcmp.ComparisonField[int]
	OrderRecords          *gcmp.ComparisonField[map[string]any]
}

// DeliveryServerRequestPreparatorComparisonFields contains field comparisons for RequestPreparator.
type DeliveryServerRequestPreparatorComparisonFields struct {
	SecondDeliveryData            *gcmp.ComparisonField[string]
	SecondDeliveryRequestPrepared *gcmp.ComparisonField[bool]
	SecondOrderPayload            *gcmp.ComparisonField[string]
	SecondOrderRequestPrepared    *gcmp.ComparisonField[bool]
}

// DeliveryServerDeliveryServerComparisonFields contains field comparisons for DeliveryServer.
type DeliveryServerDeliveryServerComparisonFields struct {
	OrderId             *gcmp.ComparisonField[*int]
	RequestDeliveryData *gcmp.ComparisonField[string]
	Result              *gcmp.ComparisonField[string]
}
