//go:build specguardian

// Code generated by spec-guardian. DO NOT EDIT.
package specguardian_test

import (
	"fmt"
	"testing"

	"github.com/mrasu/spec-guardian/guardian"
)

func TestDeliveryServer_Deliver_Conformance(t *testing.T) {
	cases := LoadDeliveryServerCases(t, "testdata/deliveryserver_deliver_cases_generated.json")

	for _, testCase := range cases {
		t.Run(testCase.Name, func(t *testing.T) {
			controller := guardian.NewInjectionController("DeliveryServer.Deliver")
			environment := NewDeliveryServerConformanceEnvironment(t, controller)
			environment.PrepareDeliverCase(t)

			input := environment.BuildDeliverInput(t, testCase.Input)
			for faultNumber := range controller.Attempts() {
				t.Run(fmt.Sprintf("fault:%d", faultNumber), func(t *testing.T) {
					environment.PrepareDeliverAttempt(t, testCase.Input)

					var actionOutput DeliveryServerDeliverOutput
					var actionErr error
					func() {
						defer controller.InjectFaultAt(faultNumber)()
						actionOutput, actionErr = environment.ExecuteDeliver(t.Context(), input)
					}()

					observedState := environment.ObserveDeliverState(t, testCase.Input, actionOutput, actionErr)
					allowedStates := environment.BuildAllowedDeliverStates(t, testCase.Allowed)

					guardian.AssertAllowed(t, allowedStates, observedState, controller.Events())
				})
			}
		})
	}
}
