//go:build specguardian

// Code generated by spec-guardian. DO NOT EDIT.
package specguardian_test

import (
	"fmt"
	"testing"

	"github.com/mrasu/spec-guardian/guardian"
)

func TestOrderServer_CreateOrder_Conformance(t *testing.T) {
	cases := LoadOrderServerCases(t, "testdata/orderserver_createorder_cases_generated.json")

	for _, testCase := range cases {
		t.Run(testCase.Name, func(t *testing.T) {
			controller := guardian.NewInjectionController("OrderServer.CreateOrder")
			environment := NewOrderServerConformanceEnvironment(t, controller)
			environment.PrepareCreateOrderCase(t)

			input := environment.BuildCreateOrderInput(t, testCase.Input)
			for faultNumber := range controller.Attempts() {
				t.Run(fmt.Sprintf("fault:%d", faultNumber), func(t *testing.T) {
					environment.PrepareCreateOrderAttempt(t, testCase.Input)

					var actionOutput OrderServerCreateOrderOutput
					var actionErr error
					func() {
						defer controller.InjectFaultAt(faultNumber)()
						actionOutput, actionErr = environment.ExecuteCreateOrder(t.Context(), input)
					}()

					observedState := environment.ObserveCreateOrderState(t, testCase.Input, actionOutput, actionErr)
					allowedStates := environment.BuildAllowedCreateOrderStates(t, testCase.Allowed)

					guardian.AssertAllowed(t, allowedStates, observedState, controller.Events())
				})
			}
		})
	}
}
