//go:build specguardian

// Code generated by spec-guardian. DO NOT EDIT.
package specguardian_test

import (
	"context"
	"testing"

	"github.com/mrasu/spec-guardian/guardian"
	"github.com/mrasu/spec-guardian/guardian/gcmp"
)

// OrderServerActions describes the application methods exercised by this role.
// This generated interface is the contract implemented by the application adapter.
type OrderServerActions interface {
	CreateOrder(context.Context, OrderServerCreateOrderInput) (OrderServerCreateOrderOutput, error)
}

// OrderServerConformanceEnvironment joins the application action adapter with its test resources.
type OrderServerConformanceEnvironment struct {
	Actions OrderServerActions
	*OrderServerEnvironment
}

// NewOrderServerConformanceEnvironment builds the adapter and resources for a conformance case.
func NewOrderServerConformanceEnvironment(t *testing.T, controller *guardian.InjectionController) *OrderServerConformanceEnvironment {
	t.Helper()
	actions, environment := BuildOrderServerConformanceComponents(t, controller)

	return &OrderServerConformanceEnvironment{
		Actions:                actions,
		OrderServerEnvironment: environment,
	}
}

// LoadOrderServerCases reads generated cases from filepath.
func LoadOrderServerCases(t *testing.T, filepath string) []OrderServerCase {
	t.Helper()
	return guardian.LoadCases[OrderServerCase](t, filepath)
}

// PrepareCreateOrderCase sets up one case and registers its cleanup.
func (e *OrderServerConformanceEnvironment) PrepareCreateOrderCase(t *testing.T) {
	e.SetupCreateOrderCase(t)
	t.Cleanup(func() {
		e.CleanupCreateOrderCase(t)
	})
}

// PrepareCreateOrderAttempt sets up one fault attempt and registers its cleanup.
func (e *OrderServerConformanceEnvironment) PrepareCreateOrderAttempt(t *testing.T, input FizzbeeOrderServerState) {
	e.SetupCreateOrderAttempt(t, input)
	t.Cleanup(func() {
		e.CleanupCreateOrderAttempt(t)
	})
}

// ExecuteCreateOrder invokes the application action.
func (e *OrderServerConformanceEnvironment) ExecuteCreateOrder(ctx context.Context, input OrderServerCreateOrderInput) (OrderServerCreateOrderOutput, error) {
	return e.Actions.CreateOrder(ctx, input)
}

// ObserveCreateOrderState collects the state and output visible after the action.
func (e *OrderServerConformanceEnvironment) ObserveCreateOrderState(t *testing.T, input FizzbeeOrderServerState, output OrderServerCreateOrderOutput, actionErr error) guardian.ObservedState[*OrderServerObservedState] {
	observedState := e.ObserveCurrentState(t)
	resultState := e.BuildObservedCreateOrderState(t, observedState, input, output, actionErr)

	return guardian.NewObservedState(&resultState)
}

// BuildAllowedCreateOrderStates maps FizzBee outcomes to comparable states.
func (e *OrderServerConformanceEnvironment) BuildAllowedCreateOrderStates(t *testing.T, allowed []FizzbeeOrderServerState) []guardian.ComparisonState[*OrderServerComparisonState] {
	allowedStates := make([]guardian.ComparisonState[*OrderServerComparisonState], len(allowed))
	for i, allowed := range allowed {
		allowedState := e.BuildAllowedCreateOrderState(t, allowed)
		allowedStates[i] = guardian.NewComparisonState(&allowedState)
	}

	return allowedStates
}

// OrderServerCase is one generated input with its allowed outcomes.
type OrderServerCase struct {
	Name    string                    `json:"name"`
	Input   FizzbeeOrderServerState   `json:"input"`
	Allowed []FizzbeeOrderServerState `json:"allowed"`
}

// FizzbeeOrderServerState contains the model parameters and fields for this role.
type FizzbeeOrderServerState struct {
	Params OrderServerParams `json:"params"`
	Fields OrderServerFields `json:"fields"`
}

// OrderServerParams contains each role's model parameters.
type OrderServerParams struct {
	OrderServer OrderServerOrderServerParams `json:"OrderServer"`
}

// OrderServerOrderServerParams contains model parameters for OrderServer.
type OrderServerOrderServerParams struct {
	RequestId string `json:"request_id"`
}

// OrderServerFields contains each role's model fields.
type OrderServerFields struct {
	DynamoDB          OrderServerDynamoDBFields          `json:"DynamoDB"`
	MySQL             OrderServerMySQLFields             `json:"MySQL"`
	RequestPreparator OrderServerRequestPreparatorFields `json:"RequestPreparator"`
	OrderServer       OrderServerOrderServerFields       `json:"OrderServer"`
}

// OrderServerDynamoDBFields contains model fields for DynamoDB.
type OrderServerDynamoDBFields struct {
	DeliveryRecords         map[string]any `json:"delivery_records"`
	OrderIdempotencyRecords map[string]any `json:"order_idempotency_records"`
}

// OrderServerMySQLFields contains model fields for MySQL.
type OrderServerMySQLFields struct {
	DeliveryPreparedCount int            `json:"delivery_prepared_count"`
	NextOrderId           int            `json:"next_order_id"`
	OrderRecords          map[string]any `json:"order_records"`
}

// OrderServerRequestPreparatorFields contains model fields for RequestPreparator.
type OrderServerRequestPreparatorFields struct {
	SecondDeliveryData            string `json:"second_delivery_data"`
	SecondDeliveryRequestPrepared bool   `json:"second_delivery_request_prepared"`
	SecondOrderPayload            string `json:"second_order_payload"`
	SecondOrderRequestPrepared    bool   `json:"second_order_request_prepared"`
}

// OrderServerOrderServerFields contains model fields for OrderServer.
type OrderServerOrderServerFields struct {
	OrderedId      *int   `json:"ordered_id"`
	RequestPayload string `json:"request_payload"`
	Result         string `json:"result"`
}

// OrderServerObservedState holds values observed from the application.
type OrderServerObservedState struct {
	Params OrderServerObservedParams
	Fields OrderServerObservedFields
}

// OrderServerObservedParams contains observed parameters for each role.
type OrderServerObservedParams struct {
	OrderServer OrderServerOrderServerObservedParams
}

// OrderServerOrderServerObservedParams contains observed parameters for OrderServer.
type OrderServerOrderServerObservedParams struct {
	RequestId *gcmp.ObservedField[string]
}

// OrderServerObservedFields contains observed fields for each role.
type OrderServerObservedFields struct {
	DynamoDB          OrderServerDynamoDBObservedFields
	MySQL             OrderServerMySQLObservedFields
	RequestPreparator OrderServerRequestPreparatorObservedFields
	OrderServer       OrderServerOrderServerObservedFields
}

// OrderServerDynamoDBObservedFields contains observed fields for DynamoDB.
type OrderServerDynamoDBObservedFields struct {
	DeliveryRecords         *gcmp.ObservedField[map[string]any]
	OrderIdempotencyRecords *gcmp.ObservedField[map[string]any]
}

// OrderServerMySQLObservedFields contains observed fields for MySQL.
type OrderServerMySQLObservedFields struct {
	DeliveryPreparedCount *gcmp.ObservedField[int]
	NextOrderId           *gcmp.ObservedField[int]
	OrderRecords          *gcmp.ObservedField[map[string]any]
}

// OrderServerRequestPreparatorObservedFields contains observed fields for RequestPreparator.
type OrderServerRequestPreparatorObservedFields struct {
	SecondDeliveryData            *gcmp.ObservedField[string]
	SecondDeliveryRequestPrepared *gcmp.ObservedField[bool]
	SecondOrderPayload            *gcmp.ObservedField[string]
	SecondOrderRequestPrepared    *gcmp.ObservedField[bool]
}

// OrderServerOrderServerObservedFields contains observed fields for OrderServer.
type OrderServerOrderServerObservedFields struct {
	OrderedId      *gcmp.ObservedField[*int]
	RequestPayload *gcmp.ObservedField[string]
	Result         *gcmp.ObservedField[string]
}

// OrderServerComparisonState configures checks for an allowed model state.
type OrderServerComparisonState struct {
	Params OrderServerComparisonParams
	Fields OrderServerComparisonFields
}

// ExpectedState identifies the FizzBee state type compared with this state.
func (actual *OrderServerComparisonState) ExpectedState() FizzbeeOrderServerState {
	return FizzbeeOrderServerState{}
}

// OrderServerComparisonParams contains parameter comparisons for each role.
type OrderServerComparisonParams struct {
	OrderServer OrderServerOrderServerComparisonParams
}

// OrderServerOrderServerComparisonParams contains parameter comparisons for OrderServer.
type OrderServerOrderServerComparisonParams struct {
	RequestId *gcmp.ComparisonField[string]
}

// OrderServerComparisonFields contains field comparisons for each role.
type OrderServerComparisonFields struct {
	DynamoDB          OrderServerDynamoDBComparisonFields
	MySQL             OrderServerMySQLComparisonFields
	RequestPreparator OrderServerRequestPreparatorComparisonFields
	OrderServer       OrderServerOrderServerComparisonFields
}

// OrderServerDynamoDBComparisonFields contains field comparisons for DynamoDB.
type OrderServerDynamoDBComparisonFields struct {
	DeliveryRecords         *gcmp.ComparisonField[map[string]any]
	OrderIdempotencyRecords *gcmp.ComparisonField[map[string]any]
}

// OrderServerMySQLComparisonFields contains field comparisons for MySQL.
type OrderServerMySQLComparisonFields struct {
	DeliveryPreparedCount *gcmp.ComparisonField[int]
	NextOrderId           *gcmp.ComparisonField[int]
	OrderRecords          *gcmp.ComparisonField[map[string]any]
}

// OrderServerRequestPreparatorComparisonFields contains field comparisons for RequestPreparator.
type OrderServerRequestPreparatorComparisonFields struct {
	SecondDeliveryData            *gcmp.ComparisonField[string]
	SecondDeliveryRequestPrepared *gcmp.ComparisonField[bool]
	SecondOrderPayload            *gcmp.ComparisonField[string]
	SecondOrderRequestPrepared    *gcmp.ComparisonField[bool]
}

// OrderServerOrderServerComparisonFields contains field comparisons for OrderServer.
type OrderServerOrderServerComparisonFields struct {
	OrderedId      *gcmp.ComparisonField[*int]
	RequestPayload *gcmp.ComparisonField[string]
	Result         *gcmp.ComparisonField[string]
}
