//go:build specguardian

// Code generated by spec-guardian. DO NOT EDIT.
package specguardian_test

import (
	"context"
	"testing"

	"github.com/mrasu/spec-guardian/guardian"
	"github.com/mrasu/spec-guardian/guardian/gcmp"
)

// ApplicationActions describes the application methods exercised by this role.
// This generated interface is the contract implemented by the application adapter.
type ApplicationActions interface {
	Read(context.Context, ApplicationReadInput) (ApplicationReadOutput, error)
	Write(context.Context, ApplicationWriteInput) (ApplicationWriteOutput, error)
}

// ApplicationConformanceEnvironment joins the application action adapter with its test resources.
type ApplicationConformanceEnvironment struct {
	Actions ApplicationActions
	*ApplicationEnvironment
}

// NewApplicationConformanceEnvironment builds the adapter and resources for a conformance case.
func NewApplicationConformanceEnvironment(t *testing.T, controller *guardian.InjectionController) *ApplicationConformanceEnvironment {
	t.Helper()
	actions, environment := BuildApplicationConformanceComponents(t, controller)

	return &ApplicationConformanceEnvironment{
		Actions:                actions,
		ApplicationEnvironment: environment,
	}
}

// LoadApplicationCases reads generated cases from filepath.
func LoadApplicationCases(t *testing.T, filepath string) []ApplicationCase {
	t.Helper()
	return guardian.LoadCases[ApplicationCase](t, filepath)
}

// PrepareReadCase sets up one case and registers its cleanup.
func (e *ApplicationConformanceEnvironment) PrepareReadCase(t *testing.T) {
	e.SetupReadCase(t)
	t.Cleanup(func() {
		e.CleanupReadCase(t)
	})
}

// PrepareReadAttempt sets up one fault attempt and registers its cleanup.
func (e *ApplicationConformanceEnvironment) PrepareReadAttempt(t *testing.T, input FizzbeeApplicationState) {
	e.SetupReadAttempt(t, input)
	t.Cleanup(func() {
		e.CleanupReadAttempt(t)
	})
}

// ExecuteRead invokes the application action.
func (e *ApplicationConformanceEnvironment) ExecuteRead(ctx context.Context, input ApplicationReadInput) (ApplicationReadOutput, error) {
	return e.Actions.Read(ctx, input)
}

// ObserveReadState collects the state and output visible after the action.
func (e *ApplicationConformanceEnvironment) ObserveReadState(t *testing.T, input FizzbeeApplicationState, output ApplicationReadOutput, actionErr error) guardian.ObservedState[*ApplicationObservedState] {
	observedState := e.ObserveCurrentState(t)
	resultState := e.BuildObservedReadState(t, observedState, input, output, actionErr)

	return guardian.NewObservedState(&resultState)
}

// BuildAllowedReadStates maps FizzBee outcomes to comparable states.
func (e *ApplicationConformanceEnvironment) BuildAllowedReadStates(t *testing.T, allowed []FizzbeeApplicationState) []guardian.ComparisonState[*ApplicationComparisonState] {
	allowedStates := make([]guardian.ComparisonState[*ApplicationComparisonState], len(allowed))
	for i, allowed := range allowed {
		allowedState := e.BuildAllowedReadState(t, allowed)
		allowedStates[i] = guardian.NewComparisonState(&allowedState)
	}

	return allowedStates
}

// PrepareWriteCase sets up one case and registers its cleanup.
func (e *ApplicationConformanceEnvironment) PrepareWriteCase(t *testing.T) {
	e.SetupWriteCase(t)
	t.Cleanup(func() {
		e.CleanupWriteCase(t)
	})
}

// PrepareWriteAttempt sets up one fault attempt and registers its cleanup.
func (e *ApplicationConformanceEnvironment) PrepareWriteAttempt(t *testing.T, input FizzbeeApplicationState) {
	e.SetupWriteAttempt(t, input)
	t.Cleanup(func() {
		e.CleanupWriteAttempt(t)
	})
}

// ExecuteWrite invokes the application action.
func (e *ApplicationConformanceEnvironment) ExecuteWrite(ctx context.Context, input ApplicationWriteInput) (ApplicationWriteOutput, error) {
	return e.Actions.Write(ctx, input)
}

// ObserveWriteState collects the state and output visible after the action.
func (e *ApplicationConformanceEnvironment) ObserveWriteState(t *testing.T, input FizzbeeApplicationState, output ApplicationWriteOutput, actionErr error) guardian.ObservedState[*ApplicationObservedState] {
	observedState := e.ObserveCurrentState(t)
	resultState := e.BuildObservedWriteState(t, observedState, input, output, actionErr)

	return guardian.NewObservedState(&resultState)
}

// BuildAllowedWriteStates maps FizzBee outcomes to comparable states.
func (e *ApplicationConformanceEnvironment) BuildAllowedWriteStates(t *testing.T, allowed []FizzbeeApplicationState) []guardian.ComparisonState[*ApplicationComparisonState] {
	allowedStates := make([]guardian.ComparisonState[*ApplicationComparisonState], len(allowed))
	for i, allowed := range allowed {
		allowedState := e.BuildAllowedWriteState(t, allowed)
		allowedStates[i] = guardian.NewComparisonState(&allowedState)
	}

	return allowedStates
}

// ApplicationCase is one generated input with its allowed outcomes.
type ApplicationCase struct {
	Name    string                    `json:"name"`
	Input   FizzbeeApplicationState   `json:"input"`
	Allowed []FizzbeeApplicationState `json:"allowed"`
}

// FizzbeeApplicationState contains the model parameters and fields for this role.
type FizzbeeApplicationState struct {
	Params ApplicationParams `json:"params"`
	Fields ApplicationFields `json:"fields"`
}

// ApplicationParams contains each role's model parameters.
type ApplicationParams struct {
	Application ApplicationApplicationParams `json:"Application"`
}

// ApplicationApplicationParams contains model parameters for Application.
type ApplicationApplicationParams struct {
	Key        string `json:"key"`
	WriteValue string `json:"write_value"`
}

// ApplicationFields contains each role's model fields.
type ApplicationFields struct {
	DB          ApplicationDBFields          `json:"DB"`
	Cache       ApplicationCacheFields       `json:"Cache"`
	Application ApplicationApplicationFields `json:"Application"`
}

// ApplicationDBFields contains model fields for DB.
type ApplicationDBFields struct {
	CommittedValues map[string]any `json:"committed_values"`
	Records         map[string]any `json:"records"`
}

// ApplicationCacheFields contains model fields for Cache.
type ApplicationCacheFields struct {
	CachedRecords map[string]any `json:"cached_records"`
}

// ApplicationApplicationFields contains model fields for Application.
type ApplicationApplicationFields struct {
	ReadResValue *string `json:"read_res_value"`
	ReadStatus   string  `json:"read_status"`
	WriteStatus  string  `json:"write_status"`
}

// ApplicationObservedState holds values observed from the application.
type ApplicationObservedState struct {
	Params ApplicationObservedParams
	Fields ApplicationObservedFields
}

// ApplicationObservedParams contains observed parameters for each role.
type ApplicationObservedParams struct {
	Application ApplicationApplicationObservedParams
}

// ApplicationApplicationObservedParams contains observed parameters for Application.
type ApplicationApplicationObservedParams struct {
	Key        *gcmp.ObservedField[string]
	WriteValue *gcmp.ObservedField[string]
}

// ApplicationObservedFields contains observed fields for each role.
type ApplicationObservedFields struct {
	DB          ApplicationDBObservedFields
	Cache       ApplicationCacheObservedFields
	Application ApplicationApplicationObservedFields
}

// ApplicationDBObservedFields contains observed fields for DB.
type ApplicationDBObservedFields struct {
	CommittedValues *gcmp.ObservedField[map[string]any]
	Records         *gcmp.ObservedField[map[string]any]
}

// ApplicationCacheObservedFields contains observed fields for Cache.
type ApplicationCacheObservedFields struct {
	CachedRecords *gcmp.ObservedField[map[string]any]
}

// ApplicationApplicationObservedFields contains observed fields for Application.
type ApplicationApplicationObservedFields struct {
	ReadResValue *gcmp.ObservedField[*string]
	ReadStatus   *gcmp.ObservedField[string]
	WriteStatus  *gcmp.ObservedField[string]
}

// ApplicationComparisonState configures checks for an allowed model state.
type ApplicationComparisonState struct {
	Params ApplicationComparisonParams
	Fields ApplicationComparisonFields
}

// ExpectedState identifies the FizzBee state type compared with this state.
func (actual *ApplicationComparisonState) ExpectedState() FizzbeeApplicationState {
	return FizzbeeApplicationState{}
}

// ApplicationComparisonParams contains parameter comparisons for each role.
type ApplicationComparisonParams struct {
	Application ApplicationApplicationComparisonParams
}

// ApplicationApplicationComparisonParams contains parameter comparisons for Application.
type ApplicationApplicationComparisonParams struct {
	Key        *gcmp.ComparisonField[string]
	WriteValue *gcmp.ComparisonField[string]
}

// ApplicationComparisonFields contains field comparisons for each role.
type ApplicationComparisonFields struct {
	DB          ApplicationDBComparisonFields
	Cache       ApplicationCacheComparisonFields
	Application ApplicationApplicationComparisonFields
}

// ApplicationDBComparisonFields contains field comparisons for DB.
type ApplicationDBComparisonFields struct {
	CommittedValues *gcmp.ComparisonField[map[string]any]
	Records         *gcmp.ComparisonField[map[string]any]
}

// ApplicationCacheComparisonFields contains field comparisons for Cache.
type ApplicationCacheComparisonFields struct {
	CachedRecords *gcmp.ComparisonField[map[string]any]
}

// ApplicationApplicationComparisonFields contains field comparisons for Application.
type ApplicationApplicationComparisonFields struct {
	ReadResValue *gcmp.ComparisonField[*string]
	ReadStatus   *gcmp.ComparisonField[string]
	WriteStatus  *gcmp.ComparisonField[string]
}
