//go:build specguardian

// Code generated by spec-guardian. DO NOT EDIT.
package specguardian_test

import (
	"fmt"
	"testing"

	"github.com/mrasu/spec-guardian/guardian"
)

func TestApplication_Read_Conformance(t *testing.T) {
	cases := LoadApplicationCases(t, "testdata/application_read_cases_generated.json")

	for _, testCase := range cases {
		t.Run(testCase.Name, func(t *testing.T) {
			controller := guardian.NewInjectionController("Application.Read")
			environment := NewApplicationConformanceEnvironment(t, controller)
			environment.PrepareReadCase(t)

			input := environment.BuildReadInput(t, testCase.Input)
			for faultNumber := range controller.Attempts() {
				t.Run(fmt.Sprintf("fault:%d", faultNumber), func(t *testing.T) {
					environment.PrepareReadAttempt(t, testCase.Input)

					var actionOutput ApplicationReadOutput
					var actionErr error
					func() {
						defer controller.InjectFaultAt(faultNumber)()
						actionOutput, actionErr = environment.ExecuteRead(t.Context(), input)
					}()

					observedState := environment.ObserveReadState(t, testCase.Input, actionOutput, actionErr)
					allowedStates := environment.BuildAllowedReadStates(t, testCase.Allowed)

					guardian.AssertAllowed(t, allowedStates, observedState, controller.Events())
				})
			}
		})
	}
}

func TestApplication_Write_Conformance(t *testing.T) {
	cases := LoadApplicationCases(t, "testdata/application_write_cases_generated.json")

	for _, testCase := range cases {
		t.Run(testCase.Name, func(t *testing.T) {
			controller := guardian.NewInjectionController("Application.Write")
			environment := NewApplicationConformanceEnvironment(t, controller)
			environment.PrepareWriteCase(t)

			input := environment.BuildWriteInput(t, testCase.Input)
			for faultNumber := range controller.Attempts() {
				t.Run(fmt.Sprintf("fault:%d", faultNumber), func(t *testing.T) {
					environment.PrepareWriteAttempt(t, testCase.Input)

					var actionOutput ApplicationWriteOutput
					var actionErr error
					func() {
						defer controller.InjectFaultAt(faultNumber)()
						actionOutput, actionErr = environment.ExecuteWrite(t.Context(), input)
					}()

					observedState := environment.ObserveWriteState(t, testCase.Input, actionOutput, actionErr)
					allowedStates := environment.BuildAllowedWriteStates(t, testCase.Allowed)

					guardian.AssertAllowed(t, allowedStates, observedState, controller.Events())
				})
			}
		})
	}
}
