// Code generated by spec-guardian. DO NOT EDIT.
package conformance

//go:generate go run github.com/mrasu/spec-guardian generate --project-dir .. --fizz-output-dir "../docs/spec/fizzbee_output" --dev
