package generate

import (
	"fmt"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/cockroachdb/errors"
	"github.com/mrasu/spec-guardian/internal/generate/renderer"
	"golang.org/x/mod/modfile"
)

type project struct {
	directory  string
	modulePath string
}

func newProject(directory string) (*project, error) {
	abs, err := filepath.Abs(directory)
	if err != nil {
		return nil, errors.Wrap(err, "resolve project directory")
	}
	modulePath, err := readModulePath(filepath.Join(abs, "go.mod"))
	if err != nil {
		return nil, err
	}
	return &project{directory: abs, modulePath: modulePath}, nil
}

func (p *project) PlanOutputFiles(fizzOutputDir string, development bool, sources *renderer.Scaffold) (map[string][]byte, bool, error) {
	root := filepath.Join(p.directory, "conformance")
	conformanceDir := filepath.Join(root, "specguardian")
	if err := requirePackage(conformanceDir, "specguardian_test"); err != nil {
		return nil, false, err
	}
	files := make(map[string][]byte)
	for role, source := range sources.RoleCases {
		files[filepath.Join(conformanceDir, strings.ToLower(role)+"_conformance_cases_generated_test.go")] = source
	}
	for role, source := range sources.RoleConformances {
		files[filepath.Join(conformanceDir, strings.ToLower(role)+"_conformance_generated_test.go")] = source
	}
	for role, source := range sources.RoleScaffolds {
		name := filepath.Join(conformanceDir, strings.ToLower(role)+"_conformance_impl_test.go")
		updated, err := planRoleFile(name, source, role)
		if err != nil {
			return nil, false, err
		}
		files[name] = updated
	}
	for name, contents := range sources.CaseData {
		files[filepath.Join(conformanceDir, "testdata", name)] = contents
	}
	directive, outside := p.generateGoSource(fizzOutputDir, development)
	files[filepath.Join(root, "specguardian.go")] = directive
	return files, outside, nil
}

func planRoleFile(name string, generated []byte, role string) ([]byte, error) {
	current, err := os.ReadFile(name)
	if errors.Is(err, os.ErrNotExist) {
		return generated, nil
	}
	if err != nil {
		return nil, errors.Wrapf(err, "read user-owned role file %s", name)
	}
	if complete, constraint := roleFileComplete(name, current, generated); complete {
		if constraint != "" {
			return append([]byte(constraint+"\n\n"), current...), nil
		}
		return current, nil
	}
	return updateRoleFile(name, current, generated, role)
}

func (p *project) generateGoSource(fizzOutputDir string, development bool) ([]byte, bool) {
	relative, err := filepath.Rel(filepath.Join(p.directory, "conformance"), fizzOutputDir)
	outside := err != nil || strings.HasPrefix(relative, ".."+string(filepath.Separator)+"..") || relative == ".."
	if outside {
		relative = fizzOutputDir
	}
	command := "//go:generate go run github.com/mrasu/spec-guardian generate --project-dir .. --fizz-output-dir " + fmt.Sprintf("%q", relative)
	if development {
		command += " --dev"
	}
	return []byte("// Code generated by spec-guardian. DO NOT EDIT.\npackage conformance\n\n" + command + "\n"), outside
}

func (p *project) developmentGoMod() ([]byte, error) {
	moduleRoot, err := commandModuleRoot()
	if err != nil {
		return nil, err
	}
	goModPath := filepath.Join(p.directory, "go.mod")
	source, err := os.ReadFile(goModPath)
	if err != nil {
		return nil, errors.Wrap(err, "read project go.mod")
	}
	parsed, err := modfile.Parse(goModPath, source, nil)
	if err != nil {
		return nil, errors.Wrap(err, "parse project go.mod")
	}
	rootReplacement, err := filepath.Rel(p.directory, moduleRoot)
	if err != nil {
		return nil, errors.Wrap(err, "resolve relative development module replacement")
	}
	rootReplacement = localReplacementPath(rootReplacement)
	guardianReplacement, err := filepath.Rel(p.directory, filepath.Join(moduleRoot, "guardian"))
	if err != nil {
		return nil, errors.Wrap(err, "resolve relative guardian module replacement")
	}
	guardianReplacement = localReplacementPath(guardianReplacement)
	if !hasModuleRequirement(parsed, specGuardianModulePath) {
		if err := parsed.AddRequire(specGuardianModulePath, specGuardianModuleVersion); err != nil {
			return nil, errors.Wrap(err, "add development module requirement")
		}
	}
	if err := parsed.AddReplace(specGuardianModulePath, "", rootReplacement, ""); err != nil {
		return nil, errors.Wrap(err, "add development module replacement")
	}
	if !hasModuleRequirement(parsed, guardianModulePath) {
		if err := parsed.AddRequire(guardianModulePath, specGuardianModuleVersion); err != nil {
			return nil, errors.Wrap(err, "add guardian development module requirement")
		}
	}
	if err := parsed.AddReplace(guardianModulePath, "", guardianReplacement, ""); err != nil {
		return nil, errors.Wrap(err, "add guardian development module replacement")
	}
	return parsed.Format()
}

func hasModuleRequirement(file *modfile.File, modulePath string) bool {
	for _, requirement := range file.Require {
		if requirement.Mod.Path == modulePath {
			return true
		}
	}
	return false
}

func localReplacementPath(relative string) string {
	if relative == "." || strings.HasPrefix(relative, "."+string(filepath.Separator)) || strings.HasPrefix(relative, ".."+string(filepath.Separator)) {
		return relative
	}
	return "." + string(filepath.Separator) + relative
}

func readModulePath(goMod string) (string, error) {
	data, err := os.ReadFile(goMod)
	if err != nil {
		return "", errors.Wrap(err, "read project go.mod")
	}
	for line := range strings.SplitSeq(string(data), "\n") {
		fields := strings.Fields(line)
		if len(fields) == 2 && fields[0] == "module" {
			return fields[1], nil
		}
	}
	return "", fmt.Errorf("project go.mod %s has no module path", goMod)
}

func requirePackage(dir, want string) error {
	entries, err := os.ReadDir(dir)
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	if err != nil {
		return errors.Wrapf(err, "read %s", dir)
	}
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") {
			continue
		}
		name := filepath.Join(dir, entry.Name())
		f, err := parser.ParseFile(token.NewFileSet(), name, nil, parser.PackageClauseOnly)
		if err != nil {
			return errors.Wrapf(err, "read package from %s", name)
		}
		if f.Name.Name != want {
			return fmt.Errorf("package in %s is %q, want %q", name, f.Name.Name, want)
		}
	}
	return nil
}

const (
	specGuardianModulePath    = "github.com/mrasu/spec-guardian"
	specGuardianModuleVersion = "v0.0.0"
	guardianModulePath        = "github.com/mrasu/spec-guardian/guardian"
)

func commandModuleRoot() (string, error) {
	_, source, _, ok := runtime.Caller(0)
	if !ok {
		return "", fmt.Errorf("locate SpecGuardian development module")
	}
	root := filepath.Clean(filepath.Join(filepath.Dir(source), "..", ".."))
	if _, err := os.Stat(filepath.Join(root, "go.mod")); err != nil {
		return "", errors.Wrapf(err, "locate SpecGuardian development module at %s", root)
	}
	return root, nil
}
